POST http://127.0.0.1:8000/motor/700
Accept: application/json
###
POST http://127.0.0.1:8000/motor/1000
Accept: application/json
###
POST http://127.0.0.1:8000/motor/1400
Accept: application/json
###
POST http://127.0.0.1:8000/motor/1700
Accept: application/json